version: "3.7"

networks:
  bilserver-core:
    external: true

services:
  minibot:
    image: ${REGISTRY_SERVER}${REPOSITORY}
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - bilserver-core
